[package]
name = " Sui Bid"
version = "0.0.0"
edition = "2026"

[dependencies]

Sui = { git = "https://github.com/Aaron1924/suiBid.git", subdir = "path/to/package", rev = "framework/testnet"}

[addresses]
